# Generated by Django 4.1.4 on 2023-04-30 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='com',
            new_name='comment',
        ),
    ]
