# Generated by Django 4.1.4 on 2023-04-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('prize', models.IntegerField()),
                ('category', models.CharField(max_length=30)),
                ('image', models.URLField()),
            ],
        ),
    ]
