# Generated by Django 4.1.4 on 2023-04-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='image',
            field=models.ImageField(upload_to='home/image'),
        ),
    ]
