# Generated by Django 4.1.4 on 2023-05-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('image', models.URLField()),
            ],
        ),
    ]
