# Generated by Django 4.1.4 on 2023-07-15 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
