# Generated by Django 4.1.4 on 2023-07-16 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_alter_variant_image'),
        ('book', '0003_delete_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='placing', max_length=20)),
                ('date', models.DateField()),
                ('addressid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell', to='book.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='placing', max_length=20)),
                ('date', models.DateField()),
                ('addressid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='book.address')),
                ('itemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='home.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
